### ISSUE TITLE
request shells

### ISSUE THREAD

**Issue by auxnet** [Shells4Free/issues#1]
desired username : dex 
i will be using shell for eggdrop

**Comment by UltimateNate** [comment]
What network are you on?

**Comment by auxnet** [comment]
network DALnet

**Comment by UltimateNate** [comment]
You need to join chat.freenode.net and PM me so I can give you the password.

**Comment by auxnet** [comment]
Verify confirmation

**Comment by UltimateNate** [comment]
Verify complete.
