### ISSUE TITLE
request open port

### ISSUE THREAD

**Issue by auxnet** [Shells4Free/issues#2]
open port : 32123

**Comment by UltimateNate** [comment]
What do you need the port for?

**Comment by auxnet** [comment]
psybnc

**Comment by UltimateNate** [comment]
Okay, but public BNCs are not allowed, if you insist on hosting one, please keep it to yourself, or perhaps to people you know.

**Comment by UltimateNate** [comment]
Port opened.

**Comment by auxnet** [comment]
thanks
